### ISSUE TITLE
Can't add clash api secret

### ISSUE THREAD

**Issue by papampi** [hiddify/hiddify-core#37]
Need to add clash api secret so it dont generate random every time and can open web without changing secret 
Tried to add the secret in config like this:
```
  "enable-clash-api": true,
  "clash-api-port": 6756,
  "clash-api-secret": "KioIofJGjak9M-rP",
  ```
  But when run the config it does not show up in the run command output:
  ```
  config options: {LogLevel:warn EnableClashApi:true ClashApiPort:6756 ClashApiSecret: GeoIPPath: .... 
  ```
  
  Tried without double quotes and it gives error:
  ```
  Running in standalone mode
Error in read and build config invalid character 'K' looking for beginning of value
```

**Comment by hiddify-com** [comment]
Please use `web-secret` instead
