### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ignoramous** [hiddify/hiddify-core#47]
*hiddify-core* has at least one GPLv3 package, [SingBox](https://github.com/SagerNet/sing-box/blob/a18400503366a46445cf5cefea83a2f2e6ddd134/LICENSE):

https://github.com/hiddify/hiddify-core/blob/4bd3392f27f85a306cd5aa1e83e9102d8a6e79e3/go.mod#L15-L16

As such, per my understanding, *hiddify-core* cannot be licensed under any other license apart from GPLv3, if the final binary statically links against any GPLv3 codebase.

**Comment by hiddify-com** [comment]
Thank you for reporting this. It has been fixed
