### ISSUE TITLE
Better Low Memory Mode for OpenWrt

### ISSUE THREAD

**Issue by Graveyard9988** [hiddify/hiddify-core#50]
please change your codes with these commits for lower memories on OpenWrt:
https://github.com/PacketCipher/hiddify-core/pull/1/commits/2208fa9f239ca36025716b935da9fbfb703a70bf
https://github.com/PacketCipher/hiddify-core/pull/3/commits/5a5070c763062ae0e86a69ed2cdfc8ab7b0e2297
https://github.com/PacketCipher/hiddify-core/pull/3/commits/36a962cdeea29c8b6badb78c10da6a40621ed50a
https://github.com/PacketCipher/hiddify-core/pull/2/commits/d778932d9eee0da020e7a5af59191f004f08d79b
https://github.com/PacketCipher/hiddify-core/pull/4/commits/989f7c47b74e00d8ff7effff400ad7cf37850108

**Comment by gigplus** [comment]
@Graveyard9988 raveshe nasbo to open wrt migi
