### ISSUE TITLE
add or support MahsaNet core in hiddifynext

### ISSUE THREAD

**Issue by hadimousavi79** [hiddify/hiddify-core#52]
سلام و خداقوت به دوولپر های گرامی hiddify
اگه ممکنه لطف کنید داخل هیدیفای نکست از هسته MahsaNet هم پشتیبانی کنید یا حداقل لطف کنید راهنمایی کنید چطوری میتونیم این هسته رو خودمون به هیدیفای نکست اضافه کنید
خیلی ممنون
@hiddify-com

**Comment by hiddify-com** [comment]
added needed parts

**Comment by hadimousavi79** [comment]
سلام و خداقوت به تیم خوب هیدیفای 
ممنون میشم لطف کنید مثل برنامه v2rayn خود کاربر بتونه دستی هسته مورد نظرش رو mahsanet یا sing-box انتخاب کنه یا حداقل سمت سورس ها به گونه ای باشه که خودمون بتونیم انتخاب کنیم برای دیوایس موردنظر با چه هسته ای بیلد بگیریم
خیلی از زحماتتون متشکرم
@hiddify-com
