### ISSUE TITLE
wrong flag for HiddifyCli

### ISSUE THREAD

**Issue by AliMehraji** [hiddify/hiddify-core#57]
in Docs about how to use [`HiddifyCli`](https://hiddify.com/app/HiddifyCli-guide/)

```bash
HiddifyCli run -c <config file or sublink> -h <HiddifyApp config file or URL>
```
The `-h` flag is help menu for the command , so it would be `-d` according to its help

```txt
-d, --hiddify string          Hiddify Setting JSON Path
```

Couldn't Find the document to make a PR

**Comment by hiddify-com** [comment]
Thanks for reporting

It is so simple also to add PR by clicking on pencil menu in the doc.
