### ISSUE TITLE
Request: Xmux for splithttp (xray core)

### ISSUE THREAD

**Issue by Graveyard9988** [hiddify/hiddify-core#79]
درود
تنها راه رفع مشکل قطعی کانفیگ های splithttp با alpn h3 این است که طبق هسته xray (آخرین ورژن استیبل) ، پارامتر xmux را طبق اسکرین شات زیر در هسته هیدیفای تعریف کنید تا مقادیر لازمه را وارد کنیم👇

![IMG_20241024_123255_671](https://github.com/user-attachments/assets/00e53d8e-3ee4-44fb-9acd-2325cda4b927)

سپاس

**Comment by hiddify-com** [comment]
اگه مستقیم کانفیگ xray وارد بشه که مشکلی نیست
ایا این تغییر توی link هست؟

**Comment by hiddify-com** [comment]
شما میتونید مستقیم xray وارد برنامه کنید
